language: ruby

matrix:
  include:
    - os: osx
      rvm: system
      sudo: required
    - os: linux
      rvm: 2.3.0

env:
  global:
    - HOMEBREW_DEVELOPER=1

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export PATH="~/.linuxbrew/bin:~/.linuxbrew/sbin:$PATH";
      export HOME=/home/linuxbrew;
      export LINUXBREW=$HOME/.linuxbrew;
      export HOMEBREW_FORCE_VENDOR_RUBY=1
      export HOMEBREW_NO_AUTO_UPDATE=1
      sudo apt-get -qq update;
      sudo apt-get install -y texinfo;
      sudo mkdir $HOME;
      sudo chown "$USER:" $HOME;
      mkdir $LINUXBREW;
      curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $LINUXBREW;
      brew tap linuxbrew/xorg;
    fi
  - brew update
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - mkdir -p $(brew --repo)/Library/Taps/dunn
  - ln -s $PWD $(brew --repo)/Library/Taps/dunn/homebrew-emacs
  - ulimit -n 1024
  # Fix linux error: Incorrect file permissions (664)
  - chmod 0644 Formula/*.rb
  - umask 022
  - git -C "/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/linuxbrew-core

script:
  - brew test-bot --no-bottle

notifications:
  email:
    on_success: never
    on_failure: always
